### ISSUE TITLE
Done with fasterr.

### ISSUE THREAD

**Issue by emruckle** [sds270-f24/fasterr#14]
@beanumber we are done with our package.

**Comment by beanumber** [comment]
This is truly spectacular work! I'm so impressed that you were able to pull this off, especially with so little (apparent) trouble. The degree of difficulty here was very high -- leveraging `Rcpp` is not easy, and not really within scope for this class, so the fact that you were able to do it is very impressive. 

One shortcoming is that the `omit_na()` function is exported and documented. This makes it very difficult for users to use and learn about the other functions. I think you could just write simple wrapper function in R that call the other functions (using the `:::` notation, if necessary). Then you can document those functions. 

I would encourage you to open an Issue on the [`tidyr` repository](https://github.com/tidyverse/tidyr/issues) and see if the developers are interested in your work. If you were able to make a contribution to this package, that would be a great accomplishment, as this is mature software that is used by millions of people everyday.
